name: Executar Monitoramento DOU

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências do Robô
        run: |
          pip install streamlit pandas playwright beautifulsoup4
          playwright install chromium

      - name: Executar Scraper
        run: python scraper.py

      - name: Salvar dados atualizados
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dados.json
          git commit -m "Dados atualizados pelo robô" || echo "Sem mudanças"
          git push
